
apiVersion: v1
kind: Service
metadata:
  name: quakewatch-service
  namespace: quakewatch
spec:
  type: NodePort
  selector:
    app: quakewatch
  ports:
    - name: http
      port: 80        # Service port
      targetPort: 5000 # Container port (Flask)
      nodePort: 30080  # Optional fixed NodePort (30000–32767)

